
<?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?>
<br />
<?php
    $methodInfo = $this->getInfo()->getAdditionalInformation('payline_payment_info');
    $name = Mage::helper('payline')->getPaymentContractType( 
                $this->getMethod()->getCode(),
                $this->getInfo()->getCcType() );
    echo isset($methodInfo) && isset($methodInfo['method']) ? $methodInfo['method'] : $name;
?>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<table>
<?php foreach ($_specificInfo as $_label => $_value):?>
    <tr>
        <td><?php echo $this->escapeHtml($_label)?>:</td>
        <td><?php echo nl2br(implode($this->getValueAsArray($_value, false), "\n"))?></td>
    </tr>
<?php endforeach; ?>
</table>
<?php endif;?>

<?php echo $this->getChildHtml()?>