<?php
$_code=$this->getMethodCode();
$_ccType = $this->getCurrrentCcType();
$_ccDisplay = 'logo';

?>

<fieldset class="form-list form-payline" id="<?php echo "payment_form_".$_code ?>" style="display:none;">
<legend align="right"><?php echo $this->getSecureLegend();?><img src="<?php echo $this->getSecureLogo() ?>" width="30px" alt="<?php echo $this->getSecureLegend();?>" title="<?php echo $this->getSecureLegend();?>"></legend>
<ul class="form-list">
	    <li>
        <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
        <?php if($_ccDisplay!='logo'): ?>
            <div class="input-box">
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" title="<?php echo $this->__('Credit Card Type') ?>" class="required-entry">
                <!--  option value=""><?php echo $this->__('--Please Select--') ?></option  -->
            <?php foreach ($this->getCcAvailableTypes() as $contract): ?>
                <option value="<?php echo $contract->getId() ?>"<?php if($contract->getId()==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $contract->getContractType(); ?></option>
            <?php endforeach ?>
            </select>
            </div>
        <?php else:?>
            <div class="input-cc-card clearfix">
            <?php foreach ($this->getCcAvailableTypes() as $contract): ?>
                <label for="<?php echo $_code ?>_cc_type_<?php echo $contract->getContractType() . '_' .$contract->getId(); ?>">
                <input name="payment[cc_type]" type="radio" value="<?php echo $contract->getId(); ?>" <?php if($contract->getId()==$_ccType): ?> selected="selected"<?php endif ?>
                        id="<?php echo $_code ?>_cc_type_<?php echo $contract->getContractType() . '_' .$contract->getId(); ?>"
                        class="validate-one-required-by-name">
                <img src="<?php echo $this->getTypeLogo($contract->getContractType());?>"  alt="<?php echo $contract->getContractType(); ?>" title="<?php echo $contract->getContractType(); ?>"/>
                </label>
            <?php endforeach ?>
            </div>
        <?php endif;?>
	    </li>
	    <!-- li>
	        <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
	        <div class="input-box">
	            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" />
	        </div>
	    </li -->
	    <li>
	        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
	        <div class="input-box">
	            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text required-entry" value="" />
	            <input type="hidden" id="<?php echo $_code ?>_card_token_pan" name="payment[card_token_pan]">
	        </div>
	    </li>
	    <li>
	        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
	        <div class="input-box">
	            <div class="v-fix">
	                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
	                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
	                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
	                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
	                <?php endforeach ?>
	                </select>
	            </div>
	            <div class="v-fix">
	                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
	                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
	                <?php foreach ($this->getCcYears() as $k=>$v): ?>
	                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
	                <?php endforeach ?>
	                </select>
	            </div>
	        </div>
	    </li>
	    <?php echo $this->getChildHtml() ?>
	    <?php if($this->hasVerification()): ?>
	    <li>
	        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
	        <div class="input-box">
	            <div class="v-fix">
	                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
	            </div>
	            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
	        </div>
	    </li>
	    <?php endif; ?>
	    <?php if($this->isWalletEnabled()): ?>
	    <li>
	        <label for="<?php echo $_code ?>_subscribe_wallet"><?php echo $this->__('Register card in my Wallet') ?></label>
	        <div class="input-box">
	            <div class="v-fix">
	                <input type="checkbox" title="<?php echo $this->__('Register card in my Wallet') ?>" class="checkbox" id="<?php echo $_code ?>_subscribe_wallet" name="payment[subscribe_wallet]" value="1" />
	            </div>
	        </div>
	    </li>
	    <?php endif; ?>
</ul>
</fieldset>

<?php if($this->getAccessKeyRef()): ?>
<script type="text/javascript">
//<![CDATA[
if (payment) {
    var paylinePayment = new PaylineDirectMethod(
                                            '<?php echo $_code ?>',
                                            '<?php echo $this->getTokenUrl() ?>',
                                            <?php echo $this->getCryptedKeys() ?>,
                                            '<?php echo $this->getAccessKeyRef() ?>',
                                            '<?php echo $this->getTokenReturnURL() ?>');

    paylinePayment.setErrors(<?php echo $this->getAjaxErrors(); ?>);

    paymentSaveAction= function(event)
    {
        paylinePayment.save();
        event.stop();
    }

    if($('payment-buttons-container') && $('payment-buttons-container').down('button')) {
        paymentContinueElem = $('payment-buttons-container').down('button');
        paymentContinueElem.removeAttribute('onclick');
        Event.observe(paymentContinueElem, 'click', paymentSaveAction);
    }
}
//]]>
</script>
<?php endif; ?>